In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [13]:
X = np.array([["Red", "Sports", "Domestic"],
              ["Red", "Sports", "Domestic"], 
              ["Red", "Sports", "Domestic"], 
              ["Yellow", "Sports", "Domestic"], 
              ["Yellow", "Sports", "Imported"],
              ["Yellow", "SUV", "Imported"], 
              ["Yellow", "SUV", "Imported"], 
              ["Yellow", "SUV", "Domestic"],
              ["Red", "SUV", "Imported"], 
              ["Red", "Sports", "Imported"]])
Y = np.array(["Yes", "No", "Yes", "No", "Yes", "No", "Yes", "No", "No", "Yes"])

In [14]:
X = pd.DataFrame(X, columns=['color', 'type', 'origin'])
X

color    type    origin
0     Red  Sports  Domestic
1     Red  Sports  Domestic
2     Red  Sports  Domestic
3  Yellow  Sports  Domestic
4  Yellow  Sports  Imported
5  Yellow     SUV  Imported
6  Yellow     SUV  Imported
7  Yellow     SUV  Domestic
8     Red     SUV  Imported
9     Red  Sports  Imported

In [15]:
#chuyen tach phan loi ve so dung dummies hoac dung onehot enconder
X_now = pd.get_dummies(X)
X_now

color_Red  color_Yellow  type_SUV  type_Sports  origin_Domestic  \
0          1             0         0            1                1   
1          1             0         0            1                1   
2          1             0         0            1                1   
3          0             1         0            1                1   
4          0             1         0            1                0   
5          0             1         1            0                0   
6          0             1         1            0                0   
7          0             1         1            0                1   
8          1             0         1            0                0   
9          1             0         0            1                0   

   origin_Imported  
0                0  
1                0  
2                0  
3                0  
4                1  
5                1  
6                1  
7                0  
8                1  
9                1

In [16]:
Y = pd.DataFrame(Y, columns=['stolen'])
Y_now = pd.get_dummies(Y, drop_first= True)
Y_now

stolen_Yes
0           1
1           0
2           1
3           0
4           1
5           0
6           1
7           0
8           0
9           1

In [17]:
from sklearn.naive_bayes import BernoulliNB

In [18]:
model = BernoulliNB()

In [19]:
model.fit(X_now, Y_now)

c:\program files\python36\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


BernoulliNB()

In [20]:
#Test data
X_new = [[1,0,1,0,1,0]] #Red, SUV, domestic

In [25]:
y_predict = model.predict(X_new)
y_predict

array([0], dtype=uint8)

##Gaussian

In [22]:
from sklearn.naive_bayes import GaussianNB

In [23]:
model1 = GaussianNB()

In [24]:
model1.fit(X_now, Y_now)

c:\program files\python36\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


GaussianNB()

In [28]:
#Test data
X_new = [[0,1,0,1,1,0]] #Yellow, sport, domestic

In [29]:
y_predict = model.predict(X_new)
y_predict

array([0], dtype=uint8)

In [30]:
X_new = [[0,1,0,1,0,1]] #Yellow, sport, imported
y_predict = model.predict(X_new)
y_predict

array([1], dtype=uint8)