In [22]:
import matplotlib.pyplot as plt
from sklearn import datasets
import numpy as np

In [2]:
digits = datasets.load_digits()

In [3]:
digits.data

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [4]:
target  = digits.target

In [5]:
target.size

1797

In [6]:
X, y = digits.data, target

In [11]:
from sklearn.svm import SVC

In [12]:
clf = SVC(gamma = 0.001, C=100)#dua tham so vao cho hoat dong tot hon
clf.fit(X_train, y_train)

SVC(C=100, gamma=0.001)

In [13]:
y_pred = clf.predict(X_test)

In [14]:
from sklearn.metrics import accuracy_score
print("Accurancy is: ", accuracy_score(y_test, y_pred))

Accurancy is:  0.9944444444444445


In [21]:
plt.show(digits.images[-5], cmap = plt.cm.gray_r, interpolation ='nearest')
plt.show()

TypeError: show() got an unexpected keyword argument 'cmap'

In [27]:
num = clf.predict([digits.data[-5]])
num

array([9])

In [28]:
from sklearn.metrics import classification_report, confusion_matrix
print("confusion_matrix: ", confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

confusion_matrix:  [[50  0  0  0  0  0  0  0  0  0]
 [ 0 47  0  0  0  0  0  0  0  0]
 [ 0  0 57  0  0  0  0  0  0  0]
 [ 0  0  0 48  0  0  0  0  0  1]
 [ 0  0  0  0 66  0  0  0  0  0]
 [ 0  0  0  0  0 50  1  0  0  0]
 [ 0  0  0  0  0  0 56  0  0  0]
 [ 0  0  0  0  0  0  0 56  0  0]
 [ 0  1  0  0  0  0  0  0 47  0]
 [ 0  0  0  0  0  0  0  0  0 60]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        50
           1       0.98      1.00      0.99        47
           2       1.00      1.00      1.00        57
           3       1.00      0.98      0.99        49
           4       1.00      1.00      1.00        66
           5       1.00      0.98      0.99        51
           6       0.98      1.00      0.99        56
           7       1.00      1.00      1.00        56
           8       1.00      0.98      0.99        48
           9       0.98      1.00      0.99        60

    accuracy                           0.99       540
